version: "3"

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./data:/usr/src/app/data
      - ./www/index.html:/usr/src/app/www/index.html
    ports:
      - "3000:3000"
